#!/bin/bash
#Get values for the .CSV 
echo "Name Team"
read team
echo "Name Stat"
read stat

truncate -s 0 output4.txt
truncate -s 0 output2.txt
truncate -s 0 output3.txt
truncate -s 0 temp.txt

while (( $team == "Warriors" )); do
  if (($stat == "FG" )); then
          sed '1b;/Warriors/!d' stats1.csv >> temp.txt	  
	  awk -F ',' '{print $2,$5}' temp.txt >> output4.txt
	 
    cat output4.txt
  else 
	  :
  fi
  break
done

